image: Visual Studio 2019
configuration: Release

install:
 - git submodule update --init --recursive --depth 1
 - mkdir build & cd build
 - cmake ..
 
build:
  project: build/quake2-RTX.sln
  parallel: true

artifacts:
  - path: build/**/*.exe
  - path: build/**/*.dll
